spring:
  application:
    name: project

  devtools:
    restart:
      enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/my_database?useSSL=false&serverTimezone=UTC
    username: root
    password: root@520518*.
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
      port: 6379
      password: 123567
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 8
          min-idle: 0
server:
  port: 8080

# springdoc-openapi swagger-ui.html doc.html
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.personal.project.controller
# knife4j
knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: user
    password: 123456
mybatis-plus:
  configuration:
    # MyBatis ??
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # ????
    db-config:
      # ?????
      id-type: auto